name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update
    - run: sudo apt-get install build-essential gnome-terminal
    - name: make
      run: make
    - name: make run
      run: make run
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: run-report
        path: run-report/
        retention-days: 30
